routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/





Route::get('/blogpost', function () {
    return view('blogpost');
})->name('blogpost');



Route::get('/single-product', function () {
    return view('single-product');
})->name('single-product');

Route::get('/search', function () {
    return view('search');
})->name('search');



Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});

Route::post('/subscribe', 'SubscriptionController@subscribe')->name('subscribe');
Route::post('/footer_contact', 'ContactAttemptController@footer')->name('contact_attempts.footer');
Route::post('/contact', 'ContactAttemptController@contact')->name('contact_attempts.contact');

Route::post('/order_marketing_materials', 'ContactAttemptController@order_marketing_materials')->name('contact_attempts.order_marketing_materials');

$pages = \App\Page::all();

foreach ($pages as $page) {
    $slug = $page->slug;
    Route::get($slug, function () use ($slug) {
        $page = \App\Page::whereSlug($slug)
            ->firstOrFail();
        switch ($slug){
            case '/':
                return view('homepage', compact('page'));
                break;
            case 'products':
                 $products = \App\Product::all();
                return view('products', compact('page', 'products'));
                break;
            case 'blog':
                return view('blog', compact('page'));
                break;
            case 'contacts':
                return view('contacts', compact('page'));
                break;
            case 'faq':
                return view('faq', compact('page'));
                break;
            case 'documentation':
                return view('documentation', compact('page'));
                break;
            case 'marketing_materials':
                $materials = \App\Material::all();
                return view('marketing_materials', compact('page', 'materials'));
                break;

            default: return view('page', compact('page'));
        }
        
    });
}

$articles = \App\Article::all();

foreach ($articles as $article) {
    Route::get($article->slug, function () {
        $slug = request()->segment(1);
        $article = \App\Article::whereSlug($slug)
            ->firstOrFail();

        return view('article', compact('article'));
    });
}

$products = \App\Product::all();

foreach ($products as $product) {
    Route::get('product/' . $product->slug, function () {
        $slug = request()->segment(2);
        $product = \App\Product::whereSlug($slug)
            ->firstOrFail();

        return view('single-product', compact('product'));
    });
}

$categories = \App\Category::all();

foreach ($categories as $category) {
    Route::get('products/category/' . $category->slug, function () {
        $slug = request()->segment(3);
        $category = \App\Category::whereSlug($slug)
            ->firstOrFail();

        return view('category', compact('category'));
    });
}

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * App\Product
 *
 * @property int $id
 * @property int $order
 * @property string $title
 * @property string|null $seo_title
 * @property string|null $product_id
 * @property string|null $excerpt
 * @property string|null $description
 * @property string|null $image
 * @property mixed|null $images
 * @property mixed|null $files
 * @property string $slug
 * @property string|null $meta_description
 * @property string|null $meta_keywords
 * @property int $top_seller
 * @property int $latest_items
 * @property int $popular_products
 * @property int $latest_solution
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property \Illuminate\Support\Carbon|null $deleted_at
 * @property-read mixed $all_images
 * @property-read mixed $link
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Packaging[] $packagings
 * @method static bool|null forceDelete()
 * @method static \Illuminate\Database\Query\Builder|\App\Product onlyTrashed()
 * @method static bool|null restore()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Product whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Product whereDeletedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Product whereDescription($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Product whereExcerpt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Product whereFiles($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Product whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Product whereImage($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Product whereImages($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Product whereLatestItems($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Product whereLatestSolution($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Product whereMetaDescription($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Product whereMetaKeywords($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Product whereOrder($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Product wherePopularProducts($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Product whereProductId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Product whereSeoTitle($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Product whereSlug($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Product whereTitle($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Product whereTopSeller($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Product whereUpdatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Product withTrashed()
 * @method static \Illuminate\Database\Query\Builder|\App\Product withoutTrashed()
 * @mixin \Eloquent
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Category[] $categories
 * @property string|null $comparison_criteria
 * @property int|null $comparison_1_enabled
 * @property int|null $comparison_2_enabled
 * @property int|null $comparison_3_enabled
 * @property string|null $comparison_1_image
 * @property string|null $comparison_2_image
 * @property string|null $comparison_3_image
 * @property string|null $comparison_1_title
 * @property string|null $comparison_2_title
 * @property string|null $comparison_3_title
 * @property string|null $comparison_0_values
 * @property string|null $comparison_1_values
 * @property string|null $comparison_2_values
 * @property string|null $comparison_3_values
 * @property-read mixed $show_comparison_table
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Product whereComparison0Values($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Product whereComparison1Enabled($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Product whereComparison1Image($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Product whereComparison1Title($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Product whereComparison1Values($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Product whereComparison2Enabled($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Product whereComparison2Image($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Product whereComparison2Title($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Product whereComparison2Values($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Product whereComparison3Enabled($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Product whereComparison3Image($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Product whereComparison3Title($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Product whereComparison3Values($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Product whereComparisonCriteria($value)
 */
class Product extends Model
{
    use SoftDeletes;

    protected $dates = ['deleted_at'];

    public function getLinkAttribute()
    {
        return url('/product/' . $this->slug);
    }

    public function getAllImagesAttribute()
    {
        $images = !empty($this->image) ? [$this->image] : [];
        if (count((array) json_decode($this->images))) {
            $images = !empty($images) ? array_merge($images, json_decode($this->images)) : json_decode($this->images);
        }

        return $images;
    }

    public function packagings()
    {
        return $this->belongsToMany(Packaging::class);
    }

    public function categories()
    {
        return $this->belongsToMany(Category::class);
    }

    public function getShowComparisonTableAttribute()
    {
        return $this->comparison_1_enabled || $this->comparison_2_enabled || $this->comparison_3_enabled;
    }

    public function getComparisonTitlesAttribute()
    {
        $titles = [];
        $titles[] = $this->title;
        if ($this->comparison_1_enabled)
            $titles[] = $this->comparison_1_title;
        if ($this->comparison_2_enabled)
            $titles[] = $this->comparison_2_title;
        if ($this->comparison_3_enabled)
            $titles[] = $this->comparison_3_title;

        return $titles;
    }

    public function getComparisonImagesAttribute()
    {
        $images = [];
        $images[] = $this->image;
        if ($this->comparison_1_enabled)
            $images[] = $this->comparison_1_image;
        if ($this->comparison_2_enabled)
            $images[] = $this->comparison_2_image;
        if ($this->comparison_3_enabled)
            $images[] = $this->comparison_3_image;

        return $images;
    }

    public function getComparisonRowsAttribute()
    {
        $rows = [];
        $criteria = $this->splitTextarea($this->comparison_criteria) ?? [];
        foreach ($criteria as $key => $criterion) {
            $row = ['title' => $criterion];
                $row['values'][] = $this->splitTextarea($this->comparison_0_values)[$key] ?? '';
            if ($this->comparison_1_enabled)
                $row['values'][] = $this->splitTextarea($this->comparison_1_values)[$key] ?? '';
            if ($this->comparison_2_enabled)
                $row['values'][] = $this->splitTextarea($this->comparison_2_values)[$key] ?? '';
            if ($this->comparison_3_enabled)
                $row['values'][] = $this->splitTextarea($this->comparison_3_values)[$key] ?? '';

            $rows[] = $row;
        }

        return $rows;
    }

    private function splitTextarea($value){
        return preg_split('/\r\n|\r|\n/', $value);
    }
}

resources/views/article.blade.php
@extends('layouts.master')
@section('title', $article->seo_title)
@section('meta_keyword', $article->meta_keywords)
@section('meta_description', $article->meta_description)
@section('content')
    <!--Site-Content-->
    <div id="#content" class="site-content">
        <div class="container">
            <!--page title-->
            <div class="page_title_area row">
                <div class="col-md-12">
                    <div class="bredcrumb">
                        <ul>
                            <li><a href="{{ url('/') }}">Home</a>
                            </li>
                            <li class="active"><a href="{{ route('blogpost') }}">blog post</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <!--/.page title-->


            <div class="single-post-page">
                <div class="row">
                    <div class="col-md-9">
                        <article class="post">
                            <div class="post-thumb-content">
                                <figure class="post-thumb">
                                    <a href="#">
                                        <img class="img-responsive" alt="thumb" src="{{Voyager::image($article->image)}}">
                                    </a>
                                </figure>
                                <!--/.post thumb-->
                                <span class="entry-date">{{$article->created_at->day}}th {{date("M", mktime(0, 0, 0, $article->created_at->month, 1))}}. {{$article->created_at->year}}</span>
                            </div>
                            <!--/.post-thumb-content-->
                            <div class="post-details">
                                <h3 class="entry-title">
                                    {{$article->title}}
                                </h3>
                                <!--/.entry title-->
                                <div class="entry-content">
                                    {!! nl2br(e($article->body)) !!}
                                </div>
                                <!--/.entry content-->
                            </div>
                            <!--/.post details-->
                            <div class="share-post">
                                <span>Share</span>
                                <a href="#"><i class="fa fa-facebook"></i></a>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                                <a href="#"><i class="fa fa-share-alt"></i></a>
                                <a href="#"><i class="fa fa-google-plus"></i></a>
                                <a href="#"><i class="fa fa-pinterest-p"></i></a>
                                <a href="#"><i class="fa fa-instagram"></i></a>
                            </div>
                            <!--/.author social-->
                        </article>
                        <!--/.post-->
                    </div>
                    <!--/.col-md-10-->
                </div>
                <!--/.row-->
            </div>
            <!--/.site-content-->
        </div>
        <!--/.container-->
    </div>
    <!--/.site-content-->
@endsection

resources/views/blog.blade.php
@extends('layouts.master')
@section('title', $page->seo_title)
@section('meta_keyword', $page->meta_keywords)
@section('meta_description', $page->meta_description)
@section('content')
    <!--Site-Content-->
    <div id="#content" class="site-content">
        <div class="container">
            <!--page title-->
            <div class="page_title_area row">
                <div class="col-md-12">
                    <div class="bredcrumb">
                        <ul>
                            <li><a href="{{ url('/') }}">Home</a>
                            </li>
                            <li class="active"><a href="{{ url('/blog') }}">Blog</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <!--/.page title-->

            <!-- content -->
            <div class="content blog-page">
                <div class="row">
                    <div class="col-md-9 col-sm-12">
                        <div class="blog_content clearfix">
                            @each('components.blog-listing-item', \App\Article::all(), 'article')
                        </div>
                        <!-- end of blog_content -->

                        {{--<div class="paginations">
                            <ul class="pagination">
                                <li><a href="#"><span class="pagicon arrow_carrot-left"></span></a>
                                </li>
                                <li><a href="#"><span>1</span></a>
                                </li>
                                <li class="active"><a href="#"><span>2</span></a>
                                </li>
                                <li><a href="#"><span>3</span></a>
                                </li>
                                <li><a href="#"><span>4</span></a>
                                </li>
                                <li><a href="#"><span>5</span></a>
                                </li>
                                <li><a href="#"><span>6</span></a>
                                </li>
                                <li><a href="#"><span class="pagicon arrow_carrot-right"></span></a>
                                </li>
                            </ul>
                        </div>--}}
                    </div>
                    <!-- end of col-md-9 -->

                    <!-- sidebar -->
                    <div class="col-md-3 col-sm-12 col-xs-12">
                        <div class="sidebar">
                            <div class="widget widget-recent-post">
                                <h3 class="widget-title">RECENT POSTS</h3>
                                <div class="recent_post">
                                    @each('components.blog-recent-posts', \App\Article::all(), 'article')
                                </div>
                            </div>
                            <!-- end of sidebar_widget -->
                        </div>
                        <!-- end of sidebar -->
                    </div>
                    <!-- end of col-md-3 -->
                </div>
                <!-- end of row-->
            </div>
            <!--/ content -->

        </div>
        <!--/.container-->
    </div>
    <!--/.about-content-->

@endsection

resources/views/faq.blade.php
@extends('layouts.master')
@section('title', $page->seo_title)
@section('meta_keyword', $page->meta_keywords)
@section('meta_description', $page->meta_description)
@section('content')
    <!--Site-Content-->
    <div id="#content" class="site-content">
        <div class="container">
            <!--page title-->
            <div class="page_title_area row">
                <div class="col-md-12">
                    <div class="bredcrumb">
                        <ul>
                            <li><a href="{{ url('/') }}">Home</a>
                            </li>
                            <li class="active"><a href="{{ url('faq') }}">FAQs</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <!--/.page title-->
            <div class="about01">
                <!-- about shop area -->
                <div class="about_our_shop_area">
                    <div class="row">
                        @each('components.faq-item', \App\Faq::all(), 'faq', 'components.empty-faq')
                    </div>
                </div>
                <!--/.about shop area-->
        </div>
        <!--/.container-->
        </div>
    </div>
    <!--/.about-content-->
@endsection

resources/views/single-product.blade.php
@extends('layouts.master')
@section('title', $product->seo_title)
@section('meta_keyword', $product->meta_keywords)
@section('meta_description', $product->meta_description)
@section('content')
    <!--Site-Content-->
    <div id="#content" class="site-content">
        <div class="container">
            <!--page title-->
            <div class="page_title_area row">
                <div class="col-md-12">
                    <div class="bredcrumb">
                        <ul>
                            <li><a href="{{ url('/') }}">Home</a>
                            </li>
                            <li class="active"><a href="{{ url('/products') }}">Products</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <!--/.page title-->
            <div class="single-produce-page no-sidebar">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <div class="single-product-details clearfix">
                            <div class="col-md-5">
                                <div class="single-slider-item">
                                    @if (count($product->all_images))
                                        @if (count($product->all_images) > 1)
                                            <ul class="owl-slider">
                                                @foreach ((array) $product->all_images as $image)
                                                    <li class="item">
                                                        <img src="{{ Voyager::image($image) }}" alt="" class="img-responsive">
                                                    </li>
                                                @endforeach
                                            </ul>
                                            <ul class="thumbnails-wrapper" id="thumbnails-wrapper">
                                                @foreach ($product->all_images as $image)
                                                    <li class="thumbnails">
                                                        <a href="#"><img src="{{ Voyager::image($image) }}" alt="" class="img-responsive">
                                                        </a>
                                                    </li>
                                                @endforeach
                                            </ul>
                                        @else
                                            <img src="{{ Voyager::image($product->image) }}" alt="{{ $product->title }}" class="img-responsive">
                                        @endif
                                    @endif
                                </div>
                            </div>
                            <div class="col-md-7">
                                <div class="right-content">
                                    <div class="product-info">
                                        <h2>{{ $product->title }}</h2>
                                        <div class="product-description">
                                            <h5 class="small-title">DESCRIPTION</h5>
                                            {!! $product->excerpt !!}
                                        </div>
                                        <div class="item-size">
                                            <h5 class="small-title">Available packaging:</h5>
                                            <div class="size-content-custom">
                                                @foreach ($product->packagings as $packaging)
                                                    <label><span>{{ $packaging->name }}</span></label>
                                                @endforeach
                                            </div>
                                        </div>
                                        <div class="product-desc">
                                            <span class="item-number"><b>Product Number:</b>  #{{ $product->product_id }}</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="product-tab">
                                <ul class="nav nav-tabs">
                                    <li class="nav active"><a data-toggle="tab" href="#tab1">PRODUCT DESCRIPTION</a>
                                    </li>
                                    <li><a data-toggle="tab" href="#tab2">Documentations</a>
                                    </li>
                                    <li><a data-toggle="tab" href="#tab3">Compare with other brands</a>
                                    </li>
                                </ul>

                                <div class="tab-content">
                                    <div id="tab1" class="tab-pane active">
                                        {!! $product->description !!}
                                    </div>
                                    <div id="tab2" class="tab-pane">
                                        {{--@dd(json_decode($product->files))--}}
                                        <div class="single-post-page">
                                            <ul class="documentations">
                                                @foreach ((array) json_decode($product->files) as $file)
                                                    <li><a href="/storage/{{ $file->download_link }}" target="_blank"><i class="fa fa-file fa-2x"></i> {{ $file->original_name }}</a></li>
                                                @endforeach
                                            </ul>
                                            <!--/.Documentation's area-->
                                        </div>
                                    </div>
                                    <div id="tab3" class="tab-pane">
                                        <div class="related-product-content">
                                            @if ($product->show_comparison_table)
                                                <div class="comparison">

                                                    <table>
                                                        <thead>
                                                        <tr>
                                                            <th class="tl tl2"></th>
                                                            <th class="qbse">
                                                                Everest
                                                            </th>
                                                            <th colspan="3" class="qbo">
                                                                Similar products of other brands
                                                            </th>
                                                        </tr>
                                                        <tr>
                                                            <th class="tl"></th>
                                                            @foreach ($product->comparison_titles as $comparison_title)
                                                                <th class="compare-heading">{{ $comparison_title }}</th>
                                                            @endforeach
                                                        </tr>
                                                        <tr>
                                                            <th></th>
                                                            @foreach ($product->comparison_images as $comparison_image)
                                                                <th class="price-info"><img
                                                                            src="{{ Voyager::image($comparison_image) }}"
                                                                            alt=""></th>
                                                            @endforeach
                                                        </tr>
                                                        </thead>
                                                        <tbody>
                                                        @foreach ($product->comparison_rows as $comparison_row)
                                                            <tr>
                                                                <td></td>
                                                                <td colspan="4">{{ $comparison_row['title'] }}</td>
                                                            </tr>
                                                            <tr class="compare-row">
                                                                <td>{{ $comparison_row['title'] }}</td>
                                                                @foreach ($comparison_row['values'] as $comparison_row_value)
                                                                    <td>{{ $comparison_row_value }}</td>
                                                                @endforeach
                                                            </tr>
                                                        @endforeach
                                                        </tbody>
                                                    </table>

                                                </div>
                                            @endif
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="related-products">
                                <div class="heading-title">
                                    <h3 class="title-text">related products</h3>
                                </div>
                                <div class="related-product-content">
                                    @foreach(\App\Product::where('active',1)->orderBy(DB::raw('RAND()'))->take(4)->get()->all() as $product)
                                    @if ($product->active==1)
                                    <div class="col-md-3 col-sm-6 col-xs-6">
                                        <div class="product-single">
                                            <a href="{{ $product->link }}">
                                            <div class="product-thumb">
                                                @if ($product->image)
                                                    <img class="img-responsive" alt="Single product" src="{{ Voyager::image($product->image) }}">
                                                @endif
                                            </div>
                                            <!--/.product-thumb-->
                                            <div class="product-info">
                                                <h2>{{ $product->title }}</h2>
                                            </div>
                                            </a>
                                            <!--/.product-info-->
                                        </div>
                                        <!--/.product-single-->
                                    </div>
                                    @endif

                                    <!--/.col-md-4-->
                                    @endforeach
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--/.container-->
    </div>
    <!--/.about-content-->
@endsection